config/routes.rb
Rails.application.routes.draw do

  resources :events

  root to: 'welcome#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  resources :events do
    resources :tickets
  end

end

app/models/event.rb
class Event < ActiveRecord::Base

  has_many :tickets
  belongs_to :owner, class_name: 'User'

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :start_time_should_be_before_end_time

  def created_by?(user)
    return false unless user
    owner_id == user.id
  end

  private
  def start_time_should_be_before_end_time
    return unless start_time && end_time

    if start_time >= end_time
      errors.add(:start_time, 'は終了時間よりも前に設定してください')
    end
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :comment, length: { maximum: 30 }, allow_blank: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :created_events, class_name: 'Event', foreign_key: :owner_id
  has_many :tickets

  def self.find_of_create_from_auth_hash(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.image_url = image_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate, except: :show

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: '作成しました'
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = current_user.created_events.find(params[:id])
  end

  def update
    @event = current_user.created_events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.destroy!
    redirect_to root_path, notice: '削除しました'
  end

  private

  def event_params
    params.require(:event).permit(
      :name, :place, :content, :start_time, :end_time
    )
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_of_create_from_auth_hash(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path, notice: 'ログインしました'
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @events = Event.where('start_time > ?', Time.zone.now).order(:start_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.haml
- now = Time.zone.now

.page-header
  %h1
    イベント情報編集

= form_for(@event, class: 'form-horizontal', role: 'form') do |f|
  - if @event.errors.any?
    .alert.alert-danger
      %ul
        - @event.errors.full_messages.each do |msg|
          %li
            = msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :place
    = f.text_field :place, class: 'form-control'
  .form-group
    =f.label :start_time
    %div
      = f.datetime_select :start_time, start_year: now.year, end_year: now.year + 1
  .form-group
    =f.label :end_time
    %div
      = f.datetime_select :end_time, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :content
    =f.text_area :content, class: 'form-control', row: 10

  = f.submit '更新', class: 'btn btn-default', data: { disable_with: '更新中' }

app/views/events/new.html.haml
- now = Time.zone.now

.page-header
  %h1 イベント作成

= form_for(@event, class: 'form-horizontal', role: 'form') do |f|
  - if @event.errors.any?
    .alert.alert-danger
      %ul
        - @event.errors.full_messages.each do |msg|
          %li
            = msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :place
    = f.text_field :place, class: 'form-control'
  .form-group
    = f.label :start_time
    %div
      = f.datetime_select :start_time, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :end_time
    %div
      = f.datetime_select :end_time, start_year: now.year, end_year: now.year + 1
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control', row: 10

  = f.submit '作成', class: 'btn btn-default', data: { disable_with: '作成中...' }

app/views/events/show.html.haml
.page-header
  %h1
    = @event.name

.row
  .col-md-8
    .panel.panel-default
      .panel-heading
        主催者
      .panel-body
        = link_to("https://twitter.com/#{@event.owner.nickname}") do
          = image_tag @event.owner.image_url
          = "@#{@event.owner.nickname}"

    .panel.panel-default
      .panel-heading
        開催時間
      .panel-body
        = @event.start_time.strftime('%Y/%m/%d %H:%M') + " - " + @event.end_time.strftime('%Y/%m/%d %H:%M')
    .panel.panel-default
      .panel-heading
        開催場所
      .panel-body
        = @event.place

    .panel.panel-default
      .panel-heading
        イベント内容
      .panel-body
        = @event.content
  .col-md-4
    - if @event.created_by?(current_user)
      = link_to 'イベントを編集する', edit_event_path(@event), class: 'btn btn-info btn-lg btn-block'
      = link_to 'イベントを削除する', event_path(@event), class: 'btn btn-danger btn-lg btn-block', method: :delete, data: { confirm: '本当に削除しますか?' }

    - if logged_in?
      %button{ class:"btn btn-primary btn-lg btn-block", data: { toggle:"modal", target:"#createTicket" } }
        参加する
      .modal.fade{ id: "createTicket", tabindex: "-1", role: "dialog", aria: { labelledby: "dialogHeader", hidden: "true" } }
        .modal-dialog
          .modal-content
            .modal-header
              %button{ type: "button", class: "close", data: { dismiss: "modal" }, aria: { hidden: "true" } }
                &times;
              %h4{ class: "modal-title", id: "dialogHeaer" }
                参加コメント
              = form_for(@event.tickets.build, url: event_tickets_path(@event), remote: true) do |f|
                .modal-body
                  =f.text_field :comment, class: 'form-control'
                .modal-footer
                  %button{ type: "button", class: "btn btn-default", data: { dismiss: "modal"} }
                    キャンセル
                  = f.button '送信', class: 'btn btn-primary', data: { disable_with: '送信中...' }


    - else
      = link_to '参加する', new_event_ticket_path(@event), class: "btn btn-primary btn-lg btn-block"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title AweomeEvents
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header.navbar.navbar-default{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'AwesomeEvents', root_path, class: 'navbar-brand'
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'イベントを作る', new_event_path
            - if logged_in?
              %li= link_to 'ログアウト', logout_path
            - else
              %li= link_to 'Twitterでログイン', '/auth/twitter'
    .container
      - if flash[:notice]
        .alert.alert-success
          = flash[:notice]
      - if flash[:alert]
        .alert.alert-danger
          = flash[:alert]
      = yield

app/views/welcome/index.html.haml
.page-header
  %h1
    イベント一覧
.list-group
  - @events.each do |event|
    = link_to(event, class: 'list-group-item') do
      %h3{class: "list-group-item-heading"}
        %u
          = event.name
      %br
      %p{class: "list-group-item-text text-info"}
        TODO: 勉強会の概要
      %span{class: "glyphicon glyphicon-user", aria: {hidden: "true"}}
      = "@#{event.owner.nickname}"
      = raw("&nbsp;")
      %span{class: "glyphicon glyphicon-map-marker", aria: {hidden: "true"}}
      = event.place
      = raw("&nbsp;")
      %span{class: "glyphicon glyphicon-time", aria: {hidden: "true"}}
      = event.start_time.strftime('%Y/%m/%d %H:%M') + " - " + event.end_time.strftime('%Y/%m/%d %H:%M')